"""
build_workbook.py
-----------------
Builds Tallaght_Gaels_Attendance_Analysis.xlsx from data/matches.csv.

Everything that can be a formula is a formula: the descriptive statistics, the
missing-value counts, the category breakdowns, the imputation, the regression
coefficients (LINEST), the predictions and the evaluation metrics. Change a
number on 'Raw Data' and the whole workbook, model included, recalculates.
"""

import csv
from pathlib import Path

from openpyxl import Workbook
from openpyxl.chart import BarChart, ScatterChart, LineChart, Reference, Series
from openpyxl.chart.trendline import Trendline
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

HERE = Path(__file__).resolve().parent
CSV_PATH = HERE / "data" / "matches.csv"
OUT_PATH = HERE / "Tallaght_Gaels_Attendance_Analysis.xlsx"

FONT = "Arial"

INK = "1B2A24"
GREEN = "0E5236"
LIGHT = "E4EDE7"
AMBER = "F6E3B8"
YELLOW = "FFFF00"

thin = Side(style="thin", color="B7C6BC")
BOX = Border(left=thin, right=thin, top=thin, bottom=thin)

# ------------------------------------------------------------------ load data

with open(CSV_PATH, newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    HEADERS = reader.fieldnames
    ROWS = list(reader)

N = len(ROWS)                       # 240
FIRST, LAST = 2, N + 1              # raw data occupies rows 2..241

NUMERIC_COLS = {
    "season", "is_home", "is_derby", "is_weekend", "is_championship", "is_senior",
    "throw_in_hour", "temperature_c", "rainfall_mm", "promo_posts",
    "home_form_points", "attendance",
}
INT_COLS = {
    "season", "is_home", "is_derby", "is_weekend", "is_championship", "is_senior",
    "throw_in_hour", "promo_posts", "home_form_points", "attendance",
}


def cast(col, value):
    if value == "":
        return None
    if col in INT_COLS:
        return int(value)
    if col in NUMERIC_COLS:
        return float(value)
    return value


COL = {name: get_column_letter(i + 1) for i, name in enumerate(HEADERS)}

wb = Workbook()

# ------------------------------------------------------------------ helpers


def style_header(ws, row=1, last_col=None, fill=GREEN):
    last_col = last_col or ws.max_column
    for c in range(1, last_col + 1):
        cell = ws.cell(row=row, column=c)
        cell.font = Font(name=FONT, bold=True, color="FFFFFF", size=10)
        cell.fill = PatternFill("solid", fgColor=fill)
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = BOX


def title(ws, text, subtitle=None):
    ws["A1"] = text
    ws["A1"].font = Font(name=FONT, bold=True, size=14, color=GREEN)
    if subtitle:
        ws["A2"] = subtitle
        ws["A2"].font = Font(name=FONT, italic=True, size=9, color="4A5A50")


def widths(ws, spec):
    for letter, w in spec.items():
        ws.column_dimensions[letter].width = w


def base_font(ws):
    for row in ws.iter_rows():
        for cell in row:
            if cell.font is None or cell.font.name != FONT:
                cell.font = Font(name=FONT, size=cell.font.size or 10,
                                 bold=cell.font.bold, italic=cell.font.italic,
                                 color=cell.font.color)


# ================================================================== Read Me

ws = wb.active
ws.title = "Read Me"
title(ws, "Tallaght Gaels CLG — match-day attendance analysis",
      "DATAH1010 Repeat Assessment, Component 2. Data Analysis & Machine Learning.")

lines = [
    ("", ""),
    ("Scenario", "Tallaght Gaels CLG is a fictional GAA club in Tallaght, Dublin 24, used as the "
                 "scenario for the 'Tallaght Community Sports Hub' club companion app."),
    ("Data status", "EVERY ROW IS FICTIONAL. The club, the opposition clubs, the results and the "
                    "attendance figures were generated by the script generate_dataset.py "
                    "(seed 42). No real person, club or match is described anywhere in this file."),
    ("Question", "Can the club predict how many people will attend a fixture, early enough to plan "
                 "stewards, parking, and how much food to order for the clubhouse?"),
    ("Dataset", f"{N} match-day records, 23 columns, seasons 2022-2026. "
                "12 of the columns are numeric."),
    ("Model", "Multiple linear regression (ordinary least squares), fitted with LINEST on the "
              "192 training rows only. The 48 test rows are never used to fit."),
    ("Recalculation", "Every figure in this workbook is a live formula. Editing a value on "
                      "'Raw Data' re-fits the model and updates every chart."),
    ("", ""),
    ("Sheet", "What it contains"),
    ("Raw Data", f"The full {N}-row dataset exactly as generated, in date order. Blank cells are "
                 "genuinely missing readings."),
    ("Data Quality", "Missing-value counts for all 23 columns, and how each gap is handled."),
    ("Descriptive Stats", "Mean, median, mode, min, max, range, standard deviation, variance, "
                          "quartiles and IQR for every numeric variable."),
    ("Category Breakdown", "Counts, shares and average attendance for each team, competition, "
                           "venue, day of week and result."),
    ("Model Data", "The modelling table: imputed and engineered features, the train/test flag, "
                   "the prediction for every row and its error. Rows 2-193 are training rows, "
                   "rows 194-241 are test rows."),
    ("Regression", "The fitted model: coefficients, standard errors, t-statistics, p-values, "
                   "train and test evaluation, a comparison against a naive baseline, and a "
                   "calculator for predicting a brand new fixture."),
    ("Charts", "Five labelled charts covering the distribution, the category differences, the "
               "strongest predictor and the model's accuracy on unseen fixtures."),
    ("", ""),
    ("Legend", "Yellow cells on the 'Regression' sheet are inputs you can type over. "
               "Everything else is calculated."),
]
r = 4
for label, text in lines:
    ws.cell(row=r, column=1, value=label).font = Font(name=FONT, bold=True, size=10, color=INK)
    c = ws.cell(row=r, column=2, value=text)
    c.font = Font(name=FONT, size=10)
    c.alignment = Alignment(wrap_text=True, vertical="top")
    ws.row_dimensions[r].height = 30 if len(text) > 95 else 15
    r += 1
widths(ws, {"A": 22, "B": 104})

# ================================================================== Raw Data

ws = wb.create_sheet("Raw Data")
ws.append(HEADERS)
for row in ROWS:
    ws.append([cast(c, row[c]) for c in HEADERS])
style_header(ws, last_col=len(HEADERS))
ws.freeze_panes = "C2"
ws.auto_filter.ref = f"A1:{get_column_letter(len(HEADERS))}{LAST}"
for i, h in enumerate(HEADERS, start=1):
    ws.column_dimensions[get_column_letter(i)].width = max(10, min(22, len(h) + 4))
for row in ws.iter_rows(min_row=2, max_row=LAST, max_col=len(HEADERS)):
    for cell in row:
        cell.font = Font(name=FONT, size=10)

note = ws.cell(row=LAST + 2, column=1,
               value="Source: generate_dataset.py (random seed 42). Fictional data created for "
                     "DATAH1010. Blank temperature_c / rainfall_mm / promo_posts cells are "
                     "deliberate missing readings, handled on 'Model Data'.")
note.font = Font(name=FONT, italic=True, size=9, color="4A5A50")

# ================================================================== Data Quality

ws = wb.create_sheet("Data Quality")
title(ws, "Data quality — completeness of every column",
      "COUNTBLANK over rows 2-241 of 'Raw Data'. Nothing here is typed in by hand.")

ws.append([])
hdr = ["Column", "Type", "Values present", "Missing", "% complete", "How it is handled"]
ws.append(hdr)
style_header(ws, row=4, last_col=6)

handling = {
    "temperature_c": "Replaced with the training-set median on 'Model Data'.",
    "rainfall_mm": "Replaced with the training-set median on 'Model Data'.",
    "promo_posts": "Replaced with the training-set median on 'Model Data'.",
}
r = 5
for h in HEADERS:
    letter = COL[h]
    ws.cell(row=r, column=1, value=h)
    ws.cell(row=r, column=2, value="numeric" if h in NUMERIC_COLS else "text")
    ws.cell(row=r, column=3, value=f"=COUNTA('Raw Data'!{letter}{FIRST}:{letter}{LAST})")
    ws.cell(row=r, column=4, value=f"=COUNTBLANK('Raw Data'!{letter}{FIRST}:{letter}{LAST})")
    ws.cell(row=r, column=5, value=f"=C{r}/{N}")
    ws.cell(row=r, column=6, value=handling.get(h, "Complete — no action needed."))
    ws.cell(row=r, column=5).number_format = "0.0%"
    for c in range(1, 7):
        ws.cell(row=r, column=c).font = Font(name=FONT, size=10)
        ws.cell(row=r, column=c).border = BOX
    r += 1

tot = r
ws.cell(row=tot, column=1, value="Total cells").font = Font(name=FONT, bold=True, size=10)
ws.cell(row=tot, column=3, value=f"=SUM(C5:C{r-1})").font = Font(name=FONT, bold=True, size=10)
ws.cell(row=tot, column=4, value=f"=SUM(D5:D{r-1})").font = Font(name=FONT, bold=True, size=10)
ws.cell(row=tot, column=5, value=f"=C{tot}/({N}*{len(HEADERS)})").font = Font(name=FONT, bold=True, size=10)
ws.cell(row=tot, column=5).number_format = "0.0%"

ws.cell(row=tot + 2, column=1,
        value="Why median and not mean: the three affected columns are all skewed "
              "(rainfall especially), so the median is the more stable stand-in. The median is "
              "taken from the training rows only, so no information from the test rows leaks "
              "into the model.").font = Font(name=FONT, italic=True, size=9, color="4A5A50")
ws.merge_cells(start_row=tot + 2, start_column=1, end_row=tot + 3, end_column=6)
ws.cell(row=tot + 2, column=1).alignment = Alignment(wrap_text=True, vertical="top")
widths(ws, {"A": 22, "B": 11, "C": 15, "D": 11, "E": 13, "F": 52})

# ================================================================== Descriptive Stats

ws = wb.create_sheet("Descriptive Stats")
title(ws, "Descriptive statistics — numeric variables",
      "All figures calculated live from 'Raw Data'. Blank cells are ignored by every function used.")

stat_cols = ["attendance", "promo_posts", "rainfall_mm", "temperature_c",
             "home_form_points", "throw_in_hour", "season"]
stats = [
    ("Count (non-blank)", "COUNT"),
    ("Missing", None),
    ("Mean", "AVERAGE"),
    ("Median", "MEDIAN"),
    ("Mode", "MODE"),
    ("Minimum", "MIN"),
    ("Maximum", "MAX"),
    ("Range", None),
    ("Standard deviation (sample)", "STDEV"),
    ("Variance (sample)", "VAR"),
    ("1st quartile", None),
    ("3rd quartile", None),
    ("Interquartile range", None),
    ("Skewness", "SKEW"),
]

ws.cell(row=4, column=1, value="Statistic")
for j, name in enumerate(stat_cols, start=2):
    ws.cell(row=4, column=j, value=name)
style_header(ws, row=4, last_col=1 + len(stat_cols))

for i, (label, fn) in enumerate(stats):
    r = 5 + i
    ws.cell(row=r, column=1, value=label).font = Font(name=FONT, bold=True, size=10)
    for j, name in enumerate(stat_cols, start=2):
        rng = f"'Raw Data'!{COL[name]}{FIRST}:{COL[name]}{LAST}"
        if label == "Missing":
            f = f"=COUNTBLANK({rng})"
        elif label == "Range":
            f = f"={get_column_letter(j)}10-{get_column_letter(j)}9"
        elif label == "1st quartile":
            f = f"=QUARTILE({rng},1)"
        elif label == "3rd quartile":
            f = f"=QUARTILE({rng},3)"
        elif label == "Interquartile range":
            f = f"={get_column_letter(j)}16-{get_column_letter(j)}15"
        elif fn == "MODE":
            f = f'=IFERROR(MODE({rng}),"no repeated value")'
        else:
            f = f"={fn}({rng})"
        c = ws.cell(row=r, column=j, value=f)
        c.font = Font(name=FONT, size=10)
        c.number_format = "#,##0" if label in ("Count (non-blank)", "Missing") else "#,##0.00"
        c.border = BOX

r = 5 + len(stats) + 1
ws.cell(row=r, column=1, value="Reading the table").font = Font(name=FONT, bold=True, size=10, color=GREEN)
for k, text in enumerate([
    "Attendance is the variable being predicted. Its spread is wide, which is the whole reason the "
    "club cannot plan on an average.",
    "season is included only to show the dataset covers five seasons; it is not used as a predictor.",
    "Skewness near zero means roughly symmetric. Rainfall is strongly right-skewed: most match days "
    "are dry and a few are very wet.",
]):
    c = ws.cell(row=r + 1 + k, column=1, value="• " + text)
    c.font = Font(name=FONT, size=9, color="4A5A50")
    ws.merge_cells(start_row=r + 1 + k, start_column=1, end_row=r + 1 + k, end_column=8)
    c.alignment = Alignment(wrap_text=True, vertical="top")
    ws.row_dimensions[r + 1 + k].height = 26

widths(ws, {"A": 28})
for j in range(2, 2 + len(stat_cols)):
    ws.column_dimensions[get_column_letter(j)].width = 16

# ================================================================== Category Breakdown

ws = wb.create_sheet("Category Breakdown")
title(ws, "Category breakdown — who plays, where, and how many turn up",
      "COUNTIF / AVERAGEIF over 'Raw Data'. The 'Average attendance' column drives two of the charts.")

att = f"'Raw Data'!${COL['attendance']}${FIRST}:${COL['attendance']}${LAST}"


def category_block(start_row, heading, column_name, values):
    ws.cell(row=start_row, column=1, value=heading).font = Font(name=FONT, bold=True, size=11, color=GREEN)
    hdr_row = start_row + 1
    for j, h in enumerate(["Category", "Matches", "Share", "Average attendance",
                           "Highest attendance", "Lowest attendance"], start=1):
        ws.cell(row=hdr_row, column=j, value=h)
    style_header(ws, row=hdr_row, last_col=6, fill=INK)
    rng = f"'Raw Data'!${COL[column_name]}${FIRST}:${COL[column_name]}${LAST}"
    for i, v in enumerate(values):
        r = hdr_row + 1 + i
        ws.cell(row=r, column=1, value=v)
        ws.cell(row=r, column=2, value=f"=COUNTIF({rng},$A{r})")
        ws.cell(row=r, column=3, value=f"=B{r}/{N}")
        ws.cell(row=r, column=4, value=f"=AVERAGEIF({rng},$A{r},{att})")
        ws.cell(row=r, column=5, value=f"=SUMPRODUCT(MAX(({rng}=$A{r})*{att}))")
        ws.cell(row=r, column=6, value=f"=SUMPRODUCT(MIN(({rng}=$A{r})*{att}+({rng}<>$A{r})*1000000))")
        ws.cell(row=r, column=3).number_format = "0.0%"
        for cc in (4, 5, 6):
            ws.cell(row=r, column=cc).number_format = "#,##0"
        for c in range(1, 7):
            ws.cell(row=r, column=c).font = Font(name=FONT, size=10)
            ws.cell(row=r, column=c).border = BOX
    return hdr_row + 1 + len(values)


teams = sorted({r["team"] for r in ROWS})
comps = ["Championship", "League", "Cup", "Challenge"]
venues = sorted({r["venue"] for r in ROWS})
days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
results = ["Win", "Draw", "Loss"]
seasons = sorted({int(r["season"]) for r in ROWS})

end = category_block(4, "By team", "team", teams)
TEAM_ROWS = (6, 6 + len(teams) - 1)
end = category_block(end + 2, "By competition", "competition", comps)
COMP_ROWS = (end - len(comps), end - 1)
end = category_block(end + 2, "By venue", "venue", venues)
end = category_block(end + 2, "By day of week", "day_of_week", days)
DAY_ROWS = (end - len(days), end - 1)
end = category_block(end + 2, "By result", "result", results)

# By season, plus the binary flags, as a separate small block
ws.cell(row=end + 2, column=1, value="By season").font = Font(name=FONT, bold=True, size=11, color=GREEN)
hdr_row = end + 3
for j, h in enumerate(["Season", "Matches", "Share", "Average attendance"], start=1):
    ws.cell(row=hdr_row, column=j, value=h)
style_header(ws, row=hdr_row, last_col=4, fill=INK)
srng = f"'Raw Data'!${COL['season']}${FIRST}:${COL['season']}${LAST}"
for i, s in enumerate(seasons):
    r = hdr_row + 1 + i
    ws.cell(row=r, column=1, value=s)
    ws.cell(row=r, column=2, value=f"=COUNTIF({srng},$A{r})")
    ws.cell(row=r, column=3, value=f"=B{r}/{N}")
    ws.cell(row=r, column=4, value=f"=AVERAGEIF({srng},$A{r},{att})")
    ws.cell(row=r, column=3).number_format = "0.0%"
    ws.cell(row=r, column=4).number_format = "#,##0"
    for c in range(1, 5):
        ws.cell(row=r, column=c).font = Font(name=FONT, size=10)
        ws.cell(row=r, column=c).border = BOX
SEASON_ROWS = (hdr_row + 1, hdr_row + len(seasons))
end = hdr_row + len(seasons)

ws.cell(row=end + 2, column=1, value="Match characteristics").font = Font(name=FONT, bold=True, size=11, color=GREEN)
hdr_row = end + 3
for j, h in enumerate(["Characteristic", "Matches", "Share", "Average attendance"], start=1):
    ws.cell(row=hdr_row, column=j, value=h)
style_header(ws, row=hdr_row, last_col=4, fill=INK)
flags = [("Home fixtures", "is_home", 1), ("Away fixtures", "is_home", 0),
         ("Local derbies", "is_derby", 1), ("Non-derbies", "is_derby", 0),
         ("Weekend throw-in", "is_weekend", 1), ("Midweek throw-in", "is_weekend", 0),
         ("Adult teams", "is_senior", 1), ("Underage teams", "is_senior", 0)]
for i, (label, col, val) in enumerate(flags):
    r = hdr_row + 1 + i
    frng = f"'Raw Data'!${COL[col]}${FIRST}:${COL[col]}${LAST}"
    ws.cell(row=r, column=1, value=label)
    ws.cell(row=r, column=2, value=f"=COUNTIF({frng},{val})")
    ws.cell(row=r, column=3, value=f"=B{r}/{N}")
    ws.cell(row=r, column=4, value=f"=AVERAGEIF({frng},{val},{att})")
    ws.cell(row=r, column=3).number_format = "0.0%"
    ws.cell(row=r, column=4).number_format = "#,##0"
    for c in range(1, 5):
        ws.cell(row=r, column=c).font = Font(name=FONT, size=10)
        ws.cell(row=r, column=c).border = BOX
FLAG_ROWS = (hdr_row + 1, hdr_row + len(flags))

widths(ws, {"A": 26, "B": 11, "C": 10, "D": 20, "E": 20, "F": 20})

# ================================================================== Model Data

ws = wb.create_sheet("Model Data")

FEATURES = ["is_home", "is_derby", "is_weekend", "is_championship", "is_senior",
            "promo_posts", "rainfall_mm", "temperature_c", "home_form_points",
            "hours_from_peak"]
# Column letters: A id, B split, C raw row, D..M features, N actual, O predicted,
# P residual, Q abs error, R squared error, S pct error, U..W raw (un-imputed) values.
FEAT_FIRST, FEAT_LAST = "D", "M"

md_headers = (["match_id", "split", "raw_row"] + FEATURES +
              ["attendance", "predicted", "residual", "abs_error", "sq_error", "pct_error", "",
               "promo_posts_raw", "rainfall_mm_raw", "temperature_c_raw"])
ws.append(md_headers)
style_header(ws, last_col=len(md_headers))

train_rows = [r for r in ROWS if r["split"] == "train"]
test_rows = [r for r in ROWS if r["split"] == "test"]
ordered = train_rows + test_rows
N_TRAIN, N_TEST = len(train_rows), len(test_rows)
TR_FIRST, TR_LAST = 2, 1 + N_TRAIN
TE_FIRST, TE_LAST = TR_LAST + 1, TR_LAST + N_TEST

for i, row in enumerate(ordered):
    r = 2 + i
    ws.cell(row=r, column=1, value=row["match_id"])
    ws.cell(row=r, column=2, value=row["split"])
    ws.cell(row=r, column=3, value=f"=MATCH($A{r},'Raw Data'!$A${FIRST}:$A${LAST},0)")

    def idx(colname):
        return f"INDEX('Raw Data'!${COL[colname]}:${COL[colname]},$C{r}+1)"

    ws.cell(row=r, column=21, value=f'=IF({idx("promo_posts")}="","",{idx("promo_posts")})')
    ws.cell(row=r, column=22, value=f'=IF({idx("rainfall_mm")}="","",{idx("rainfall_mm")})')
    ws.cell(row=r, column=23, value=f'=IF({idx("temperature_c")}="","",{idx("temperature_c")})')

    ws.cell(row=r, column=4, value=f'={idx("is_home")}')
    ws.cell(row=r, column=5, value=f'={idx("is_derby")}')
    ws.cell(row=r, column=6, value=f'={idx("is_weekend")}')
    ws.cell(row=r, column=7, value=f'={idx("is_championship")}')
    ws.cell(row=r, column=8, value=f'={idx("is_senior")}')
    ws.cell(row=r, column=9, value=f'=IF($U{r}="",Regression!$B$6,$U{r})')
    ws.cell(row=r, column=10, value=f'=IF($V{r}="",Regression!$B$7,$V{r})')
    ws.cell(row=r, column=11, value=f'=IF($W{r}="",Regression!$B$8,$W{r})')
    ws.cell(row=r, column=12, value=f'={idx("home_form_points")}')
    ws.cell(row=r, column=13, value=f'=ABS({idx("throw_in_hour")}-Regression!$B$9)')
    ws.cell(row=r, column=14, value=f'={idx("attendance")}')
    ws.cell(row=r, column=15,
            value=f"=SUMPRODUCT(Regression!$C$14:$L$14,${FEAT_FIRST}{r}:${FEAT_LAST}{r})+Regression!$B$15")
    ws.cell(row=r, column=16, value=f"=$N{r}-$O{r}")
    ws.cell(row=r, column=17, value=f"=ABS($P{r})")
    ws.cell(row=r, column=18, value=f"=$P{r}^2")
    ws.cell(row=r, column=19, value=f"=$Q{r}/$N{r}")

    for c in range(1, 24):
        cell = ws.cell(row=r, column=c)
        cell.font = Font(name=FONT, size=9)
        if c in (15, 16, 17):
            cell.number_format = "#,##0.0"
        elif c == 18:
            cell.number_format = "#,##0"
        elif c == 19:
            cell.number_format = "0.0%"
    ws.cell(row=r, column=2).fill = PatternFill(
        "solid", fgColor=LIGHT if row["split"] == "train" else AMBER)

ws.freeze_panes = "D2"
widths(ws, {"A": 11, "B": 8, "C": 9, "N": 12, "O": 12, "P": 11, "Q": 11, "R": 11, "S": 11,
            "T": 3, "U": 16, "V": 16, "W": 17})
for c in range(4, 14):
    ws.column_dimensions[get_column_letter(c)].width = 15

note_row = TE_LAST + 2
for k, text in enumerate([
    f"Rows {TR_FIRST}-{TR_LAST} (shaded light green) are the {N_TRAIN} training rows. "
    f"Rows {TE_FIRST}-{TE_LAST} (shaded amber) are the {N_TEST} test rows, held back entirely.",
    "The split was fixed in advance with random seed 42 and stored in the dataset, so re-opening "
    "the workbook can never reshuffle it.",
    "Columns U-W hold the raw, un-imputed readings. Columns I-K substitute the training median "
    "when a reading is blank. hours_from_peak is engineered: the number of hours between "
    "throw-in and 3pm, treating an early and a late throw-in as equally awkward.",
]):
    c = ws.cell(row=note_row + k, column=1, value="• " + text)
    c.font = Font(name=FONT, italic=True, size=9, color="4A5A50")
    ws.merge_cells(start_row=note_row + k, start_column=1, end_row=note_row + k, end_column=13)
    c.alignment = Alignment(wrap_text=True, vertical="top")
    ws.row_dimensions[note_row + k].height = 26

# ================================================================== Regression

ws = wb.create_sheet("Regression")
title(ws, "Multiple linear regression — predicting match-day attendance",
      "Fitted with LINEST on the 192 training rows only. Yellow cells are inputs you can change.")

Y = f"'Model Data'!$N${TR_FIRST}:$N${TR_LAST}"
X = f"'Model Data'!${FEAT_FIRST}${TR_FIRST}:${FEAT_LAST}${TR_LAST}"
LINEST = f"LINEST({Y},{X},TRUE,TRUE)"
K = len(FEATURES)

setup = [
    ("Training rows", f'=COUNTIF(\'Model Data\'!$B$2:$B${TE_LAST},"train")', "#,##0", False),
    ("Test rows", f'=COUNTIF(\'Model Data\'!$B$2:$B${TE_LAST},"test")', "#,##0", False),
    ("Median promo_posts (training rows only)", f"=MEDIAN('Model Data'!$U${TR_FIRST}:$U${TR_LAST})", "#,##0.0", False),
    ("Median rainfall_mm (training rows only)", f"=MEDIAN('Model Data'!$V${TR_FIRST}:$V${TR_LAST})", "#,##0.0", False),
    ("Median temperature_c (training rows only)", f"=MEDIAN('Model Data'!$W${TR_FIRST}:$W${TR_LAST})", "#,##0.0", False),
    ("Peak throw-in hour used by hours_from_peak", 15, "#,##0", True),
]
for i, (label, val, fmt, is_input) in enumerate(setup):
    r = 4 + i
    ws.cell(row=r, column=1, value=label).font = Font(name=FONT, size=10, bold=True)
    c = ws.cell(row=r, column=2, value=val)
    c.number_format = fmt
    c.font = Font(name=FONT, size=10, color="0000FF" if is_input else "000000")
    if is_input:
        c.fill = PatternFill("solid", fgColor=YELLOW)
    c.border = BOX

# --- coefficients
ws.cell(row=11, column=1, value="Fitted coefficients").font = Font(name=FONT, bold=True, size=12, color=GREEN)
labels = {12: "Feature", 13: "Plain-language meaning", 14: "Coefficient (people)",
          16: "Standard error", 17: "t statistic", 18: "p value (two-tailed)",
          19: "Significant at 5%?"}
for r, lab in labels.items():
    ws.cell(row=r, column=1, value=lab).font = Font(name=FONT, bold=True, size=10)

MEANINGS = {
    "is_home": "Playing at home rather than away",
    "is_derby": "Opponent is one of the four local rivals",
    "is_weekend": "Throw-in falls on Saturday or Sunday",
    "is_championship": "Championship rather than league, cup or challenge",
    "is_senior": "An adult team rather than an underage team",
    "promo_posts": "Each extra club social media post about the fixture",
    "rainfall_mm": "Each extra millimetre of rain on the day",
    "temperature_c": "Each extra degree Celsius",
    "home_form_points": "Each extra league point from the last five games",
    "hours_from_peak": "Each hour the throw-in moves away from 3pm",
}

ws.cell(row=12, column=2, value="(intercept)")
ws.cell(row=12, column=2).font = Font(name=FONT, bold=True, size=9)
ws.cell(row=12, column=2).alignment = Alignment(horizontal="center")
for j, feat in enumerate(FEATURES):
    col = 3 + j
    letter = get_column_letter(col)
    ws.cell(row=12, column=col, value=feat)
    ws.cell(row=13, column=col, value=MEANINGS[feat])
    ws.cell(row=14, column=col, value=f"=INDEX({LINEST},1,{K - j})")
    ws.cell(row=16, column=col, value=f"=INDEX({LINEST},2,{K - j})")
    ws.cell(row=17, column=col, value=f"={letter}14/{letter}16")
    ws.cell(row=18, column=col, value=f"=TDIST(ABS({letter}17),$B$22,2)")
    ws.cell(row=19, column=col, value=f'=IF({letter}18<0.05,"yes","no")')
    for r in (12, 13, 14, 16, 17, 18, 19):
        c = ws.cell(row=r, column=col)
        c.border = BOX
        c.alignment = Alignment(wrap_text=True, vertical="top", horizontal="center")
        c.font = Font(name=FONT, size=9, bold=(r in (12, 14)))
    ws.cell(row=14, column=col).number_format = "#,##0.0"
    ws.cell(row=16, column=col).number_format = "#,##0.0"
    ws.cell(row=17, column=col).number_format = "#,##0.00"
    ws.cell(row=18, column=col).number_format = "0.0000"

ws.cell(row=14, column=2, value=f"=INDEX({LINEST},1,{K + 1})")
ws.cell(row=16, column=2, value=f"=INDEX({LINEST},2,{K + 1})")
ws.cell(row=15, column=1, value="Intercept, used by every prediction").font = Font(name=FONT, bold=True, size=10)
ws.cell(row=15, column=2, value="=$B$14")
for r_, bold in ((14, True), (15, True), (16, False)):
    c = ws.cell(row=r_, column=2)
    c.number_format = "#,##0.0"
    c.font = Font(name=FONT, size=10, bold=bold, color=GREEN if r_ == 15 else "000000")
    c.border = BOX
    c.alignment = Alignment(horizontal="center")

ws.cell(row=20, column=1,
        value="Read a coefficient as: holding everything else constant, this is how many extra "
              "people attend. A local derby is worth roughly as much as a championship tie and a "
              "home advantage combined.")
ws.cell(row=20, column=1).font = Font(name=FONT, italic=True, size=9, color="4A5A50")

# --- fit statistics
ws.cell(row=22, column=1, value="Degrees of freedom").font = Font(name=FONT, bold=True, size=10)
ws.cell(row=22, column=2, value=f"=INDEX({LINEST},4,2)")
ws.cell(row=23, column=1, value="F statistic").font = Font(name=FONT, bold=True, size=10)
ws.cell(row=23, column=2, value=f"=INDEX({LINEST},4,1)")
ws.cell(row=24, column=1, value="Standard error of the estimate").font = Font(name=FONT, bold=True, size=10)
ws.cell(row=24, column=2, value=f"=INDEX({LINEST},3,2)")
for r in (22, 23, 24):
    ws.cell(row=r, column=2).number_format = "#,##0.00"
    ws.cell(row=r, column=2).font = Font(name=FONT, size=10)
    ws.cell(row=r, column=2).border = BOX

# --- evaluation
ws.cell(row=26, column=1, value="Evaluation").font = Font(name=FONT, bold=True, size=12, color=GREEN)
for j, h in enumerate(["Metric", "Training set", "Test set (unseen)", "What it means"], start=1):
    ws.cell(row=27, column=j, value=h)
style_header(ws, row=27, last_col=4, fill=INK)

md = "'Model Data'!"
tr_sq, te_sq = f"{md}$R${TR_FIRST}:$R${TR_LAST}", f"{md}$R${TE_FIRST}:$R${TE_LAST}"
tr_abs, te_abs = f"{md}$Q${TR_FIRST}:$Q${TR_LAST}", f"{md}$Q${TE_FIRST}:$Q${TE_LAST}"
tr_pct, te_pct = f"{md}$S${TR_FIRST}:$S${TR_LAST}", f"{md}$S${TE_FIRST}:$S${TE_LAST}"
tr_y, te_y = f"{md}$N${TR_FIRST}:$N${TR_LAST}", f"{md}$N${TE_FIRST}:$N${TE_LAST}"

eval_rows = [
    ("Rows", f"=$B$4", f"=$B$5", "#,##0",
     "192 fixtures to learn from, 48 the model has never seen."),
    ("R squared", f"=INDEX({LINEST},3,1)", f"=1-SUM({te_sq})/DEVSQ({te_y})", "0.000",
     "Share of the variation in attendance the model explains. 1.0 would be perfect."),
    ("RMSE (people)", f"=SQRT(SUM({tr_sq})/$B$4)", f"=SQRT(SUM({te_sq})/$B$5)", "#,##0.0",
     "Typical error, with big misses punished hardest."),
    ("MAE (people)", f"=AVERAGE({tr_abs})", f"=AVERAGE({te_abs})", "#,##0.0",
     "Average size of a miss, in people through the gate."),
    ("MAPE", f"=AVERAGE({tr_pct})", f"=AVERAGE({te_pct})", "0.0%",
     "Average miss as a percentage of the real crowd."),
    ("Largest single miss (people)", f"=MAX({tr_abs})", f"=MAX({te_abs})", "#,##0",
     "Worst case. Worth knowing before promising the caterer a number."),
]
for i, (label, ftr, fte, fmt, meaning) in enumerate(eval_rows):
    r = 28 + i
    ws.cell(row=r, column=1, value=label).font = Font(name=FONT, bold=True, size=10)
    ws.cell(row=r, column=2, value=ftr).number_format = fmt
    ws.cell(row=r, column=3, value=fte).number_format = fmt
    ws.cell(row=r, column=4, value=meaning)
    for c in range(1, 5):
        cell = ws.cell(row=r, column=c)
        cell.border = BOX
        if c != 1:
            cell.font = Font(name=FONT, size=10)
        cell.alignment = Alignment(wrap_text=(c == 4), vertical="top")

base_r = 28 + len(eval_rows) + 1
ws.cell(row=base_r, column=1, value="Baseline comparison").font = Font(name=FONT, bold=True, size=12, color=GREEN)
ws.cell(row=base_r + 1, column=1, value="Naive baseline: always predict the training mean")
ws.cell(row=base_r + 1, column=2, value=f"=AVERAGE({tr_y})").number_format = "#,##0.0"
ws.cell(row=base_r + 2, column=1, value="Baseline RMSE on the test set")
ws.cell(row=base_r + 2, column=2,
        value=f"=SQRT(SUMPRODUCT(({te_y}-$B${base_r + 1})^2)/$B$5)").number_format = "#,##0.0"
ws.cell(row=base_r + 3, column=1, value="Model RMSE on the test set")
ws.cell(row=base_r + 3, column=2, value=f"=$C$30").number_format = "#,##0.0"
ws.cell(row=base_r + 4, column=1, value="Improvement over the baseline")
ws.cell(row=base_r + 4, column=2,
        value=f"=1-$B${base_r + 3}/$B${base_r + 2}").number_format = "0.0%"
for r in range(base_r + 1, base_r + 5):
    ws.cell(row=r, column=1).font = Font(name=FONT, size=10, bold=True)
    ws.cell(row=r, column=2).font = Font(name=FONT, size=10)
    ws.cell(row=r, column=2).border = BOX

# --- calculator
calc = base_r + 6
ws.cell(row=calc, column=1, value="Predict a new fixture").font = Font(name=FONT, bold=True, size=12, color=GREEN)
ws.cell(row=calc + 1, column=1,
        value="Type over the yellow cells in the input row. This is the same calculation the web "
              "app runs on its Attendance planner page.")
ws.cell(row=calc + 1, column=1).font = Font(name=FONT, italic=True, size=9, color="4A5A50")

DEFAULTS = {"is_home": 1, "is_derby": 1, "is_weekend": 1, "is_championship": 1, "is_senior": 1,
            "promo_posts": 8, "rainfall_mm": 0.4, "temperature_c": 14.0,
            "home_form_points": 11, "hours_from_peak": 0}
NAME_ROW, INPUT_ROW, HELP_ROW = calc + 3, calc + 4, calc + 5
ws.cell(row=NAME_ROW, column=1, value="Feature").font = Font(name=FONT, bold=True, size=10)
ws.cell(row=INPUT_ROW, column=1, value="Your fixture").font = Font(name=FONT, bold=True, size=10)
ws.cell(row=HELP_ROW, column=1, value="Meaning").font = Font(name=FONT, bold=True, size=10)
for j, feat in enumerate(FEATURES):
    col = 3 + j
    ws.cell(row=NAME_ROW, column=col, value=feat)
    c = ws.cell(row=INPUT_ROW, column=col, value=DEFAULTS[feat])
    c.fill = PatternFill("solid", fgColor=YELLOW)
    c.font = Font(name=FONT, size=10, color="0000FF", bold=True)
    ws.cell(row=HELP_ROW, column=col, value=MEANINGS[feat])
    for r in (NAME_ROW, INPUT_ROW, HELP_ROW):
        cell = ws.cell(row=r, column=col)
        cell.border = BOX
        cell.alignment = Alignment(wrap_text=True, vertical="top", horizontal="center")
        if r != INPUT_ROW:
            cell.font = Font(name=FONT, size=9, bold=(r == NAME_ROW))

pred_r = HELP_ROW + 2
ws.cell(row=pred_r, column=1, value="Predicted attendance").font = Font(name=FONT, bold=True, size=11)
ws.cell(row=pred_r, column=2,
        value=f"=SUMPRODUCT($C${INPUT_ROW}:$L${INPUT_ROW},$C$14:$L$14)+$B$15")
ws.cell(row=pred_r, column=2).number_format = "#,##0"
ws.cell(row=pred_r + 1, column=1, value="Planning range (plus or minus one RMSE)").font = Font(name=FONT, bold=True, size=11)
ws.cell(row=pred_r + 1, column=2,
        value=f'=TEXT(MAX(0,$B${pred_r}-$C$30),"#,##0")&" to "&TEXT($B${pred_r}+$C$30,"#,##0")')
ws.cell(row=pred_r + 2, column=1, value="Crowd band shown in the app").font = Font(name=FONT, bold=True, size=11)
ws.cell(row=pred_r + 2, column=2,
        value=f'=IF($B${pred_r}<300,"Light",IF($B${pred_r}<500,"Steady",'
              f'IF($B${pred_r}<700,"Busy","Very busy")))')
for r in (pred_r, pred_r + 1, pred_r + 2):
    ws.cell(row=r, column=2).fill = PatternFill("solid", fgColor=LIGHT)
    ws.cell(row=r, column=2).border = BOX
    ws.cell(row=r, column=2).font = Font(name=FONT, size=11, bold=True, color=GREEN)

ws.cell(row=pred_r + 4, column=1,
        value="Band thresholds: under 300 Light, 300-499 Steady, 500-699 Busy, 700 or more Very "
              "busy. The app shows the band rather than a single number because the honest error "
              "on an unseen fixture is about 70 people, and a band does not pretend otherwise.")
ws.cell(row=pred_r + 4, column=1).font = Font(name=FONT, italic=True, size=9, color="4A5A50")
ws.merge_cells(start_row=pred_r + 4, start_column=1, end_row=pred_r + 5, end_column=8)
ws.cell(row=pred_r + 4, column=1).alignment = Alignment(wrap_text=True, vertical="top")

widths(ws, {"A": 38, "B": 14})
for j in range(3, 3 + K):
    ws.column_dimensions[get_column_letter(j)].width = 15

# ================================================================== Charts

cs = wb.create_sheet("Charts")
title(cs, "Charts", "Every chart reads live from the sheets behind it.")

cb = wb["Category Breakdown"]

# 1. Average attendance by team
ch1 = BarChart()
ch1.type = "col"
ch1.title = "Average attendance by team"
ch1.y_axis.title = "Average attendance (people)"
ch1.x_axis.title = "Team"
ch1.add_data(Reference(cb, min_col=4, min_row=TEAM_ROWS[0] - 1, max_row=TEAM_ROWS[1]), titles_from_data=True)
ch1.set_categories(Reference(cb, min_col=1, min_row=TEAM_ROWS[0], max_row=TEAM_ROWS[1]))
ch1.height, ch1.width = 9, 17
ch1.legend = None
cs.add_chart(ch1, "A4")

# 2. Average attendance by competition
ch2 = BarChart()
ch2.type = "col"
ch2.title = "Average attendance by competition"
ch2.y_axis.title = "Average attendance (people)"
ch2.x_axis.title = "Competition"
ch2.add_data(Reference(cb, min_col=4, min_row=COMP_ROWS[0] - 1, max_row=COMP_ROWS[1]), titles_from_data=True)
ch2.set_categories(Reference(cb, min_col=1, min_row=COMP_ROWS[0], max_row=COMP_ROWS[1]))
ch2.height, ch2.width = 9, 17
ch2.legend = None
cs.add_chart(ch2, "L4")

# 3. Average attendance by day of week
ch3 = BarChart()
ch3.type = "col"
ch3.title = "Average attendance by day of the week"
ch3.y_axis.title = "Average attendance (people)"
ch3.x_axis.title = "Day"
ch3.add_data(Reference(cb, min_col=4, min_row=DAY_ROWS[0] - 1, max_row=DAY_ROWS[1]), titles_from_data=True)
ch3.set_categories(Reference(cb, min_col=1, min_row=DAY_ROWS[0], max_row=DAY_ROWS[1]))
ch3.height, ch3.width = 9, 17
ch3.legend = None
cs.add_chart(ch3, "A24")

# 4. Promotional posts vs attendance (scatter, with trendline)
mdws = wb["Model Data"]
ch4 = ScatterChart()
ch4.title = "Club social posts vs attendance (all 240 matches)"
ch4.x_axis.title = "Promotional posts before the fixture"
ch4.y_axis.title = "Attendance (people)"
ch4.style = 13
xref = Reference(mdws, min_col=9, min_row=TR_FIRST, max_row=TE_LAST)
yref = Reference(mdws, min_col=14, min_row=TR_FIRST, max_row=TE_LAST)
s = Series(yref, xref, title="Match")
s.marker.symbol = "circle"
s.marker.size = 5
s.graphicalProperties.line.noFill = True
s.trendline = Trendline(trendlineType="linear")
ch4.series.append(s)
ch4.height, ch4.width = 9, 17
cs.add_chart(ch4, "L24")

# 5. Predicted vs actual on the test set
ch5 = ScatterChart()
ch5.title = "Predicted vs actual attendance — 48 unseen fixtures"
ch5.x_axis.title = "Predicted attendance (people)"
ch5.y_axis.title = "Actual attendance (people)"
ch5.style = 13
px = Reference(mdws, min_col=15, min_row=TE_FIRST, max_row=TE_LAST)
py = Reference(mdws, min_col=14, min_row=TE_FIRST, max_row=TE_LAST)
s2 = Series(py, px, title="Test fixture")
s2.marker.symbol = "circle"
s2.marker.size = 6
s2.graphicalProperties.line.noFill = True
s2.trendline = Trendline(trendlineType="linear")
ch5.series.append(s2)
ch5.height, ch5.width = 9, 17
cs.add_chart(ch5, "A44")

cs.cell(row=63, column=1,
        value="A perfect model would put every point on a straight 45-degree line in the "
              "predicted-vs-actual chart. The points sit close to it but not on it, which is the "
              "visual version of an R squared of about 0.83.").font = \
    Font(name=FONT, italic=True, size=9, color="4A5A50")

# ------------------------------------------------------------------ save

for sheet in wb.worksheets:
    sheet.sheet_view.showGridLines = sheet.title in ("Raw Data", "Model Data")

wb.save(OUT_PATH)
print("wrote", OUT_PATH)
print(f"train rows {TR_FIRST}-{TR_LAST}  test rows {TE_FIRST}-{TE_LAST}")
